dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="2.2"

matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: 2.7
      env: DJANGO=2.1
    - python: 2.7
      env: DJANGO=2.2
    - python: 3.4
      env: DJANGO=2.1
    - python: 3.4
      env: DJANGO=2.2

services:
  - memcached
  - mysql
  - redis-server
  - postgresql

cache: pip

install: pip install tox tox-travis coveralls

before_script:
  - psql -c 'CREATE USER cachalot SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE cachalot OWNER cachalot;' -U postgres
  - mysql -u root -e 'CREATE DATABASE cachalot;'

script: tox

after_success: coveralls
