dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

services:
  - memcached
  - mysql
  - redis-server
  - postgresql

cache: pip

install: pip install tox tox-travis coveralls

before_script:
  - psql -c 'CREATE USER cachalot SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE cachalot OWNER cachalot;' -U postgres
  - mysql -u root -e 'CREATE DATABASE cachalot;'

script: tox

after_success: coveralls
